#Student Name: Melissa Vaziri
#Student Number: #101366349


# Question 1: Do you actually believe the licensing information comment provided to be accurate? What do you think the ramifications might be of code generated by proprietary training data?

# If I’m being honest, the licensing information comment provided by ChatGPT is likely not accurate. This is because it is a computer program that can make mistakes, including generating false information or incorrect code. AI often draws from many sources, and since we don’t always know where that information comes from, it can raise concerns similar to academic misconduct and make it unclear who actually owns the data.

# Question 2: Do you think the names you requested exhibit bias towards a particular ethnicity? Try asking for another 51 names, but this time indicate you want surnames originating from Scotland, China, Russia, or Japan (your choice). Include both lists of names as comments in your code

# In my opinion, the first set of names was not biased toward any particular ethnicity because I did not specify one. However, the second list of 51 names was more specific since I asked for surnames originating from Scotland. Because the request was more targeted, that list naturally reflected a cultural bias, whereas the earlier list was more general.

#Names that GPT provided based on the ethnicity chosen (Scotland)

# 1. Ainsworth
# 2. Aitken
# 3. Anderson
# 4. Baird
# 5. Barclay
# 6. Bell
# 7. Blair
# 8. Boyd
# 9. Brodie
# 10. Brown
# 11. Buchanan
# 12. Cameron
# 13. Campbell
# 14. Carmichael
# 15. Chisholm
# 16. Clark
# 17. Craig
# 18. Crawford
# 19. Cumming
# 20. Douglas
# 21. Drummond
# 22. Duncan
# 23. Ferguson
# 24. Finlay
# 25. Forbes
# 26. Fraser
# 27. Gordon
# 28. Graham
# 29. Grant
# 30. Hamilton
# 31. Henderson
# 32. Innes
# 33. Johnston
# 34. Kennedy
# 35. Kerr
# 36. King
# 37. Lindsay
# 38. MacDonald
# 39. MacGregor
# 40. Mackenzie
# 41. MacLeod
# 42. MacMillan
# 43. Marshall
# 44. Murray
# 45. Robertson
# 46. Ross
# 47. Sinclair
# 48. Stewart
# 49. Sutherland
# 50. Wallace
# 51. Watson

#Original List Of Names Without Ethnicity: Adams, Allen, Anderson, Bailey, Baker, Barnes, Bennett, Brooks, Brown, Campbell, Carter, Clark, Collins, Cook, Cooper, Cox, Davis, Diaz, Edwards, Evans, Fisher, Foster, Garcia, Gomez, Gonzalez, Gray, Green, Hall, Harris, Henderson, Hill, Howard, Hughes, Jackson, Johnson, King, Lee, Lewis, Long, Martin, Miller, Mitchell, Moore, Morgan, Morris, Murphy, Nelson, Parker, Perez, Perry, Phillips


#Chatgpt Part:

# This code is written in Python 3.
# Licensing / Usage Notice:
# This code was generated by ChatGPT. It is provided without warranty.
# You may use, modify, or distribute it freely, but you are responsible for
# verifying correctness, safety, and suitability for your project.

from typing import Literal

def quartile_sort_position(name: str) -> Literal[
    "before_25",
    "between_25_50",
    "between_50_75",
    "after_75"
]:

    # Normalize the name for consistent alphabetical comparison.
    normalized_name = name.strip().title()

    # Quartile boundaries (only the three names given).
    q25 = "Clark"
    q50 = "Gonzalez"
    q75 = "Lewis"

    # Lexicographic comparison.
    if normalized_name < q25:
        return "before_25"
    elif normalized_name < q50:
        return "between_25_50"
    elif normalized_name < q75:
        return "between_50_75"
    else:
        return "after_75"

#My Part Of The Requirements without chat gpt:

#Creating A Function Called "checking_as_many_names"
def checking_as_many_names():
    #This Is Basically Creating A Variable, which stores names into a list
    names_list = []
    # This was my post-conditioned loop, which provides the user the chance to enter as many names as they want, but as soon as they type n, it quits them from the program (option b)
    while True:
        name = input ("Enter a name to check (N to quit): ")
        if name.lower() == "n":
            print("Goodbye! See You Next Time")
            break

        # Add the name to the list by appending it
        names_list.append(name)

        # Print the current list, and the quartile position for the name that was entered
        print(f"This is the current list: {names_list}")
        print(f"Quartile position for '{name}': {quartile_sort_position(name)}")


    # Print the list after the user quits
    print(f"Here Is The Final Display Of: {names_list}")
# Call your function
checking_as_many_names()
